name: window_manager
description: This plugin allows Flutter desktop apps to resizing and repositioning the window.
version: 0.4.3
homepage: https://github.com/leanflutter/window_manager

platforms:
  linux:
  macos:
  windows:

topics:
  - window
  - window-resize
  - window-manager
  - desktop
  - desktop-window

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  screen_retriever: ^0.2.0
  window_manager_linux: ^1.0.1
  window_manager_macos: ^1.0.1
  window_manager_platform_interface: ^1.0.1
  window_manager_windows: ^1.0.1

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2

flutter:
  plugin:
    platforms:
      linux:
        default_package: window_manager_linux
      macos:
        default_package: window_manager_macos
      windows:
        default_package: window_manager_windows
